-- Generated from generator/demo_specs/aws-philippines-remittance-cross-border.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-remittance-cross-border
-- This is the schema that is actually deployed for PH_REMITTANCE_CROSS_BORDER.

-- Alerts fire on the bottom tail of Avg Transfer Time
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_TRANSFER_TIME) AS T
  FROM RAW.TRANSACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_TRANSFER_TIME <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_TRANSFER_TIME), 2) AS AVG_TRANSFER_TIME,
  ROUND(AVG(f.KPI_US_PH_SHARE), 2) AS AVG_US_PH_SHARE,
  ROUND(AVG(f.KPI_MIDDLE_EAST_SHARE), 2) AS AVG_MIDDLE_EAST_SHARE,
  ROUND(AVG(f.KPI_AVG_FEE_RATE), 2) AS AVG_FEE_RATE
FROM RAW.TRANSACTIONS f
JOIN RAW.BSP_REPORTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_TRANSFER_TIME), 2) AS AVG_TRANSFER_TIME,
  ROUND(AVG(f.KPI_US_PH_SHARE), 2) AS AVG_US_PH_SHARE,
  ROUND(AVG(f.KPI_MIDDLE_EAST_SHARE), 2) AS AVG_MIDDLE_EAST_SHARE,
  ROUND(AVG(f.KPI_AVG_FEE_RATE), 2) AS AVG_FEE_RATE
FROM RAW.TRANSACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_TRANSFER_TIME) AS KPI_AVG_TRANSFER_TIME, AVG(KPI_US_PH_SHARE) AS KPI_US_PH_SHARE, AVG(KPI_MIDDLE_EAST_SHARE) AS KPI_MIDDLE_EAST_SHARE, AVG(KPI_AVG_FEE_RATE) AS KPI_AVG_FEE_RATE FROM RAW.TRANSACTIONS),
     en AS (SELECT SUM(KPI_REMITTANCE_VOLUME) AS KPI_REMITTANCE_VOLUME, SUM(KPI_ACTIVE_CORRIDORS) AS KPI_ACTIVE_CORRIDORS, SUM(KPI_TRANSACTIONS_MTD) AS KPI_TRANSACTIONS_MTD FROM RAW.BSP_REPORTS)
  SELECT 1 AS SORT_ORDER, 'Remittance Volume' AS TITLE, KPI_REMITTANCE_VOLUME AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_REMITTANCE_VOLUME) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Corridors' AS TITLE, KPI_ACTIVE_CORRIDORS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_CORRIDORS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Transfer Time' AS TITLE, KPI_AVG_TRANSFER_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_TRANSFER_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'hrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Transactions (MTD)' AS TITLE, KPI_TRANSACTIONS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_TRANSACTIONS_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'US→PH Share' AS TITLE, KPI_US_PH_SHARE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_US_PH_SHARE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Middle East Share' AS TITLE, KPI_MIDDLE_EAST_SHARE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MIDDLE_EAST_SHARE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Fee Rate' AS TITLE, KPI_AVG_FEE_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_FEE_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
