-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Cross-Border Remittance Analytics & Corridor Intelligence
-- ============================================================================
USE DATABASE REMITTANCE_OPS;
USE SCHEMA ML;

-- ML.FORECAST: CORRIDOR_VOLUME_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CORRIDOR_VOLUME_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CORRIDOR_TIMESERIES'),
  SERIES_COLNAME => 'CORRIDOR_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'DAILY_VOLUME_PHP'
  
);

CREATE OR REPLACE TABLE ML.CORRIDOR_VOLUME_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.CORRIDOR_VOLUME_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: CORRIDOR_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CORRIDOR_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CORRIDOR_TIMESERIES'),
  SERIES_COLNAME => 'CORRIDOR_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'DAILY_VOLUME_PHP',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CORRIDOR_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CORRIDOR_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CORRIDOR_TIMESERIES'), SERIES_COLNAME => 'CORRIDOR_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'DAILY_VOLUME_PHP'));

