-- ============================================================================
-- 99_RESET.SQL — Reset Cross-Border Remittance Analytics & Corridor Intelligence to clean demo state
-- ============================================================================
USE DATABASE REMITTANCE_OPS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_TRANSACTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_CORRIDORS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CORRIDOR_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.SENDER_BEHAVIOR REFRESH;
ALTER DYNAMIC TABLE CURATED.PAYOUT_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.CORRIDOR_TIMESERIES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM REMITTANCE_OPS.RAW.TRANSACTIONS → 2400000
-- SELECT COUNT(*) FROM REMITTANCE_OPS.RAW.PAYOUT_AGENTS → 14500
-- SELECT COUNT(DISTINCT CORRIDOR_ID) FROM REMITTANCE_OPS.CURATED.CORRIDOR_ANALYTICS → 210

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_CORRIDORS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_TRANSACTIONS RESUME;
